#!/bin/bash

redir_cmd() {
	if (( SILENT )); then "$@" &>/dev/null
	else "$@"
	fi
}

if [[ $1 == 'ls' ]]; then
	tmux ls | grep -v -- '-[0-9]\+:'
	exit
fi

if [[ -n $TMUX ]]; then echo 'Already in tmux.'; exit 1; fi

if [[ -z $1 ]]; then
	base='main'
else
	base=$1
fi

data=$(tmux ls 2>/dev/null)

if [[ -z $(echo "$data" | grep "^$base:") ]]; then
	exec tmux new -s "$base"
else
	for sess in $(echo "$data" | grep "^$base-[0-9]\+:" | grep -v '(attached)' | cut -d: -f1); do
		tmux kill-session -t $sess
	done

	if [[ -n $(echo "$data" | grep "^$base:" | grep -v '(attached)') ]]; then
		exec tmux attach -t $base
	fi

	for i in {2..0}; do
		new=$base-$(( RANDOM % 100 ))
		SILENT=$i redir_cmd tmux new -s "$new" -t "$base" -d
		if (( !$? )); then
			exec tmux attach -t "$new" \; set -q destroy-unattached on
		fi
	done
fi
